Changing permissions of gradlew and application scripts

diff --git a/application b/application
--- a/application
+++ b/application
@@ -1,1 +1,78 @@
-#!/bin/bashif [[ -f "./env.sh" ]]; then  echo "Use env variables from file ${PWD}/env.sh"  source ./env.shfi#DB_CONTAINER_NAME="spring-postgres"workDir="${WORKING_DIRECTORY:=~/Workspace}"help() {  echo "  Usage:    ./application init - init working directory    ./application clean - clean working directory    ./application build - run JUnit tests to check app health (-skipTests arg to skip tests) and build jar    ./application up - launch application  "}up() {  cd "${workDir}/weather-sdk/build/libs" || exit  java -jar weather-sdk.jar}build() {  cd "${workDir}/weather-sdk" || exit  ./gradlew clean  if [[ "$1" = "-skipTests" ]] || ./gradlew test; then    echo "Application is building..."    ./gradlew bootJar  else    echo "Tests failed. See test report or send -skipTests arg to skip tests"  fi}clean() {#  remove working directory  echo "Removing working directory ${workDir}..."  rm -rf "${workDir}"}init() {#  init working directory  mkdir -p "${workDir}"  cd "${workDir}" || exit# git clone  if [[ ! -d "weather-sdk" ]]; then    git clone https://github.com/ValerijE/weather-sdk.git  fi  cd "weather-sdk" || exit  git checkout master}case $1 inhelp)  help  ;;init)  init  ;;clean)  clean  ;;build)  build $2  ;;up)  up  ;;*)  echo "$1 command is not valid"  exit 1  ;;esac
+#!/bin/bash
+
+if [[ -f "./env.sh" ]]; then
+  echo "Use env variables from file ${PWD}/env.sh"
+  source ./env.sh
+fi
+
+#DB_CONTAINER_NAME="spring-postgres"
+workDir="${WORKING_DIRECTORY:=~/Workspace}"
+
+help() {
+  echo "
+  Usage:
+    ./application init - init working directory
+    ./application clean - clean working directory
+    ./application build - run JUnit tests to check app health (-skipTests arg to skip tests) and build jar
+    ./application up - launch application
+  "
+}
+
+up() {
+  cd "${workDir}/weather-sdk/build/libs" || exit
+  java -jar weather-sdk-*.jar
+}
+
+build() {
+  cd "${workDir}/weather-sdk" || exit
+
+  ./gradlew clean
+
+  if [[ "$1" = "-skipTests" ]] || ./gradlew test; then
+    echo "Application is building..."
+    ./gradlew bootJar
+  else
+    echo "Tests failed. See test report or send -skipTests arg to skip tests"
+  fi
+}
+
+clean() {
+#  remove working directory
+  echo "Removing working directory ${workDir}..."
+  rm -rf "${workDir}"
+}
+
+init() {
+#  init working directory
+  mkdir -p "${workDir}"
+  cd "${workDir}" || exit
+
+# git clone
+  if [[ ! -d "weather-sdk" ]]; then
+    git clone https://github.com/ValerijE/weather-sdk.git
+  fi
+  cd "weather-sdk" || exit
+  git checkout master
+}
+
+case $1 in
+help)
+  help
+  ;;
+init)
+  init
+  ;;
+clean)
+  clean
+  ;;
+build)
+  build $2
+  ;;
+up)
+  up
+  ;;
+*)
+  echo "$1 command is not valid"
+  exit 1
+  ;;
+esac
